### ISSUE TITLE
Proposal: use specific types for file and folder instead of aliases

### ISSUE THREAD

**Issue by h-mayorquin** [catalystneuro/neuroconv#493] opened 2023-06-21 15:32 UTC
Right now we use these aliases for typing:

```
FilePathType = TypeVar("FilePathType", str, Path)
FolderPathType = TypeVar("FolderPathType", str, Path)
OptionalFilePathType = Optional[FilePathType]
OptionalFolderPathType = Optional[FolderPathType]
```
https://github.com/catalystneuro/neuroconv/blob/fbd7caf376c1f4ddf624bf9dca7da48bf74b3bcf/src/neuroconv/utils/types.py#LL6C1-L9C50

I have the vague memory that @bendichter was removing the Optional versions of them in some of the interfaces at the end of the last year. Not sure if there was a reversal of the approach. 

I think it will be better if we removed this aliases and instead use the types expliclity ("Explicit is better than implicit").  That is, in the following:

```python
    # First alternative
    def __init__(self, file_path: FilePathType, verbose: bool = True):
    
     # Second alternative
    def __init__(self, file_path: Union[str, Path], verbose: bool=True):
```

I think the second alternative is better. Why? I have some points:

1) An important use of type hints is for static analysis and linterns so they help detect bugs. They are failing me here in that regard:

![image](https://github.com/catalystneuro/neuroconv/assets/6429509/b2623b89-bcd9-46ad-ab7d-747f7bdca36d)

That is, they are producing a false positive.

2) Another use of typing is to work as self-documentation and improve readability. I really don't think that `FilePathType` is a better self-documentation than the `Union[str, Path]` ( or `str | Path`). I think that users who see the signature and know what a type is will understand that the argument expects either a str or a type. Plus, our consistent use of the name `folder_path` and `file_path` is clear enough for that semantic distinction as well, no need for an extra type. Why ofuscate this by having a definition somewhere else? This maybe would make sense if the object was something complicated like the [numpy array type](https://numpy.org/doc/stable/reference/typing.html#numpy.typing.ArrayLike) which we expected to change and we wanted to abstract that away from the users but `str | Path` is unlikely to change.

3) They also have the small friction that I need to remember where to import them from. Specially when I am doing projects outside of neuroconv such as in conversion projects. Importing directly from typing in the standard library is easy and less friction. Less friction is good.

This is a low priority issue. But I was working on https://github.com/catalystneuro/neuroconv/pulls and this came up. I have been thinking about if for a while so I wanted to write it down.

**Comment by CodyCBakerPhD** [comment] 2023-06-21 16:00
duplicate of https://github.com/catalystneuro/neuroconv/issues/261

Already WIP on https://github.com/catalystneuro/neuroconv/pull/264, which would also validate that files/folders exist on the system

Only thing holding it up is extensive testing that it wouldn't completely disrupt the existing source validation workflow but if you're motivated to check out the PR, try it out in practice, and try to find issues that would be great

**Comment by h-mayorquin** [comment] 2023-06-21 16:11
Oh, great, thanks for pointing that out @CodyCBakerPhD. I might after we are done with the current conversion.

**Closed** 2024-08-21 18:17 UTC
Labels: documentation, priority: low, discussion
